### ISSUE TITLE
error uviloop dependency with pip install

### ISSUE THREAD

**Issue by francescosave** [ShelterCare/backend#2]
```ps
franc@DESKTOP-P3KJLUH MINGW64 ~/Desktop/ShelterCare/backend (master)
$ pip install --no-cache-dir -r requirements.txt
Collecting annotated-types==0.7.0 (from -r requirements.txt (line 1))
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting anyio==4.6.0 (from -r requirements.txt (line 2))
  Downloading anyio-4.6.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi==2024.8.30 (from -r requirements.txt (line 3))
  Downloading certifi-2024.8.30-py3-none-any.whl.metadata (2.2 kB)
Collecting click==8.1.7 (from -r requirements.txt (line 4))
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: dnspython==2.6.1 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 5)) (2.6.1)
Collecting email_validator==2.2.0 (from -r requirements.txt (line 6))
  Downloading email_validator-2.2.0-py3-none-any.whl.metadata (25 kB)
Collecting fastapi==0.115.0 (from -r requirements.txt (line 7))
  Downloading fastapi-0.115.0-py3-none-any.whl.metadata (27 kB)
Collecting fastapi-cli==0.0.5 (from -r requirements.txt (line 8))
  Downloading fastapi_cli-0.0.5-py3-none-any.whl.metadata (7.0 kB)
Collecting flake8==7.1.1 (from -r requirements.txt (line 9))
  Downloading flake8-7.1.1-py2.py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: h11==0.14.0 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 10)) (0.14.0)
Requirement already satisfied: httpcore==1.0.5 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 11)) (1.0.5)
Collecting httptools==0.6.1 (from -r requirements.txt (line 12))
  Downloading httptools-0.6.1-cp312-cp312-win_amd64.whl.metadata (3.7 kB)
Collecting httpx==0.27.2 (from -r requirements.txt (line 13))
  Downloading httpx-0.27.2-py3-none-any.whl.metadata (7.1 kB)
Collecting idna==3.10 (from -r requirements.txt (line 14))
  Downloading idna-3.10-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: iniconfig==2.0.0 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 15)) (2.0.0)
Requirement already satisfied: Jinja2==3.1.4 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 16)) (3.1.4)
Collecting markdown-it-py==3.0.0 (from -r requirements.txt (line 17))
  Downloading markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: MarkupSafe==2.1.5 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 18)) (2.1.5)
Collecting mccabe==0.7.0 (from -r requirements.txt (line 19))
  Downloading mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting mdurl==0.1.2 (from -r requirements.txt (line 20))
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging==24.1 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 21)) (24.1)
Requirement already satisfied: pluggy==1.5.0 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 22)) (1.5.0)
Collecting pycodestyle==2.12.1 (from -r requirements.txt (line 23))
  Downloading pycodestyle-2.12.1-py2.py3-none-any.whl.metadata (4.5 kB)
Collecting pydantic==2.9.2 (from -r requirements.txt (line 24))
  Downloading pydantic-2.9.2-py3-none-any.whl.metadata (149 kB)
Collecting pydantic_core==2.23.4 (from -r requirements.txt (line 25))
  Downloading pydantic_core-2.23.4-cp312-none-win_amd64.whl.metadata (6.7 kB)
Collecting pyflakes==3.2.0 (from -r requirements.txt (line 26))
  Downloading pyflakes-3.2.0-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: Pygments==2.18.0 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 27)) (2.18.0)
Collecting pytest==8.3.3 (from -r requirements.txt (line 28))
  Downloading pytest-8.3.3-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: python-dotenv==1.0.1 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 29)) (1.0.1)
Collecting python-multipart==0.0.10 (from -r requirements.txt (line 30))
  Downloading python_multipart-0.0.10-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: PyYAML==6.0.2 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 31)) (6.0.2)
Collecting rich==13.8.1 (from -r requirements.txt (line 32))
  Downloading rich-13.8.1-py3-none-any.whl.metadata (18 kB)
Collecting shellingham==1.5.4 (from -r requirements.txt (line 33))
  Downloading shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: sniffio==1.3.1 in c:\users\franc\appdata\local\programs\python\python312\lib\site-packages (from -r requirements.txt (line 34)) (1.3.1)
Collecting starlette==0.38.6 (from -r requirements.txt (line 35))
  Downloading starlette-0.38.6-py3-none-any.whl.metadata (6.0 kB)
Collecting typer==0.12.5 (from -r requirements.txt (line 36))
  Downloading typer-0.12.5-py3-none-any.whl.metadata (15 kB)
Collecting typing_extensions==4.12.2 (from -r requirements.txt (line 37))
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting uvicorn==0.30.6 (from -r requirements.txt (line 38))
  Downloading uvicorn-0.30.6-py3-none-any.whl.metadata (6.6 kB)
Collecting uvloop==0.20.0 (from -r requirements.txt (line 39))
  Downloading uvloop-0.20.0.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 32.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
          main()
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "C:\Users\franc\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 332, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 302, in _get_build_requires
          self.run_setup()
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          self.run_setup()
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
        File "C:\Users\franc\AppData\Local\Temp\pip-build-env-x6vdyd8k\overlay\Lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
          exec(code, locals())
          exec(code, locals())
        File "<string>", line 8, in <module>
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by francescosave** [comment]
Installed fastapi just with a single manual command in terminal and execute successfully.
I use windows and I will check uvloop of windows

**Comment by francescosave** [comment]
My fastapi apps with windows operating system runs well without it.
I removed uvloop==0.20.0 reference in requirements,txt.

How can we maintain compatibility between different operating systems ?
Do we use any different requirements file of windows os?
